import React, { Component } from "react";
import { withLocalize } from "react-localize-redux";
import Table from '../../../../../components/table';

// Start: Data For Section Pitcher
const titlePitcherTable1 = {
    dot: false,
    text: '対セ・リーグ チーム別成績',
}
const headerPitcherTable1 = ["対戦", "防御率", "登板", "完投", "完封", "無四球", "勝利", "敗戦", "ホールド", "HP", "セーブ", "勝率",
    "投球回", "打者", "被安打", "被本塁打", "奪三振", "奪三振率", "与四球", "与死球", "暴投", "ボーク", "失点", "自責点",]
const dataPitcherTable1 = [
    {
        item: [
            { img: '/img/Swallow.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/Carp.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/DeNA.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/Dragons.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/TIgers.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
]

const titlePitcherTable2 = {
    dot: false,
    text: '対パ・リーグ チーム別成績',
}
const headerPitcherTable2 = ["対戦", "防御率", "登板", "完投", "完封", "無四球", "勝利", "敗戦", "ホールド", "HP", "セーブ", "勝率",
    "投球回", "打者", "被安打", "被本塁打", "奪三振", "奪三振率", "与四球", "与死球", "暴投", "ボーク", "失点", "自責点",]
const dataPitcherTable2 = [
    {
        item: [
            { img: '/img/Lions.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/Hawks.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/Fighters.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/Bufalloes.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { img: '/img/Marines.png' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
]

const titlePitcherTable3 = {
    dot: false,
    text: '月別成績',
}
const headerPitcherTable3 = ["月", "防御率", "登板", "完投", "完封", "無四球", "勝利", "敗戦", "ホールド", "HP", "セーブ", "勝率",
    "投球回", "打者", "被安打", "被本塁打", "奪三振", "奪三振率", "与四球", "与死球", "暴投", "ボーク", "失点", "自責点",]
const dataPitcherTable3 = [
    {
        item: [
            { text: '3月' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '4月' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '5月' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '6月' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '7月' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
]

const titlePitcherTable4 = {
    dot: false,
    text: '左右打者別成績',
}
const headerPitcherTable4 = ["打者", "被打率", "打数", "被安打", "被本塁打", "奪三振", "与四球", "与死球",]
const dataPitcherTable4 = [
    {
        item: [
            { text: '右打者' },
            { text: '.234' },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '右打者' },
            { text: '.234' },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
]

const titlePitcherTable5 = {
    dot: false,
    text: '球場別成績',
}
const headerPitcherTable5 = ["球場", "防御率", "登板", "完投", "完封", "無四球", "勝利", "敗戦", "ホールド", "HP", "セーブ", "勝率",
    "投球回", "打者", "被安打", "被本塁打", "奪三振", "奪三振率", "与四球", "与死球", "暴投", "ボーク", "失点", "自責点",]
const dataPitcherTable5 = [
    {
        item: [
            { text: '東京ドーム' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '神宮' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '横浜' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: 'ナゴヤドーム' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '甲子園' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: 'メットライフ' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '京セラD大阪' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '鹿児島' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '熊本' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '札幌ドーム' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '楽天生命パーク' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: 'マツダスタジアム' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
    {
        item: [
            { text: '三次' },
            { text: 26 },
            { text: 26 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
        ]
    },
]
// End: Data For Table Pitcher

class PitcherContent extends Component {
    render() {
        return(
            <div>
                <Table header={headerPitcherTable1} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataPitcherTable1} isShowOptionTable={false} titleTable={titlePitcherTable1} />
                <Table header={headerPitcherTable2} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataPitcherTable2} isShowOptionTable={false} titleTable={titlePitcherTable2} />
                <Table header={headerPitcherTable3} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataPitcherTable3} isShowOptionTable={false} titleTable={titlePitcherTable3} />
                <Table header={headerPitcherTable4} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataPitcherTable4} isShowOptionTable={false} titleTable={titlePitcherTable4} />
                <Table header={headerPitcherTable5} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataPitcherTable5} isShowOptionTable={false} titleTable={titlePitcherTable5} />
            </div>
        )
    }
}

export default withLocalize(PitcherContent);