import React, { Component } from "react";
import "./style.scss";
import { withLocalize } from "react-localize-redux";
import Table from '../../../../components/table';

const titleHitting = {
    dot: false,
    text: '打撃成績',
}
const headerHitting = ['年度', 'チーム', '試合', '打席', '打数', '得点', '安打', '二塁打', '三塁打', '本塁打', '塁打',
    '打点', '三振', '四球', '敬遠', '死球', '犠打', '犠飛', '盗塁', '盗塁刺', '併殺打', '失策', '打率', '長打率', '出塁率', 'OPS',]
const dataHitting = [
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
    {
        item: [
            { text: '通算' },
            { text: 0 },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
            { text: '3.26' },
        ]
    },
]

const titlePitching = {
    dot: false,
    text: '投手成績',
}
const headerPitching = ['年度', 'チーム', '防御率', '登板', '先発', '完投', '完封', '無四球', '交代完了', '勝数', '負数', 'セーブ', 'ホールド',
    'HP', '勝率', '投球回', '打者', '被安打', '被本塁打', '与四球', '与死球', '奪三振', '暴投', 'ボーク', '失点', '自責点', '被打率']
const dataPitching = [
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '2007' },
            { img: '/img/Giants.png' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
    {
        item: [
            { text: '通算' },
            { text: '326' },
            { text: '26' },
            { text: '26' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '15' },
            { text: '4' },
            { text: '0' },
            { text: '0' },
            { text: '0' },
            { text: '.798' },
            { text: '170 1/3' },
            { text: '705' },
            { text: '19.9' },
            { text: '12.5' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
            { text: '326' },
        ]
    },
]

class PerformanceByYear extends Component {

    componentDidMount() {
        let tables = document.getElementsByClassName('wrap-table');
        for (let i = 0; i < tables.length; i++) {
            let itemCenter = tables[i].getElementsByClassName('item-center');
            for (let i = 0; i < itemCenter.length; i++) {
                if(i === itemCenter.length - 1){
                    let td = itemCenter[i].getElementsByClassName('border-0');
                    td[0].setAttribute('colspan', '2');
                }
            }
        }
    }

    openTab = (e, tabName) => {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(tabName).style.display = "block";
        e.currentTarget.className += " active";
    }

    render() {
        return(
            <div className="year">
                <div className="year-control">
                    <div className="left">
                        <h2 className="title">過去シーズン成績</h2>
                        <div className="wrapper-tab">
                            <button className="tablinks active" onClick={(e) => this.openTab(e, 'pitcher')} id="defaultOpen" >1軍</button>
                            <button className="tablinks" onClick={(e) => this.openTab(e, 'batter')} >2軍</button>
                        </div>
                    </div>
                    <div className="right">
                        <div className="block-button">
                            <button type="button">CSVダウンロード</button>
                        </div>
                    </div>
                </div>
                <div className="year-content">
                    <div id="pitcher" className="tabcontent">
                        <Table header={headerHitting} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataHitting} isShowOptionTable={false} titleTable={titleHitting} />
                        <Table header={headerPitching} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataPitching} isShowOptionTable={false} titleTable={titlePitching} />
                    </div>

                    <div id="batter" className="tabcontent">
                    </div>
                </div>
            </div>
        )
    }
}

export default withLocalize(PerformanceByYear);