import React, { Component } from "react";
import { withLocalize } from "react-localize-redux";
import Table from '../../../../components/table';
import "./style.scss";

const titlePerformance = {
    dot: false,
    text: '投手成績',
}
const headerPerformance = ['', '試合日付', '相手', '勝敗SH', '完投', '当初', '投球回', '打者', '被本塁打', '与四球', '与死球',
    '奪三振', '暴投', 'ボーク', '失点', '自責点', '防御率', 'BB/9', 'K/9', 'K/BB', 'WHIP', '被安打',]
const dataPerformance = [
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '4月' },
            { text: '' },
            { text: '4勝0敗0S0H' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '5月' },
            { text: '' },
            { text: '4勝0敗0S0H' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '6月' },
            { text: '' },
            { text: '4勝0敗0S0H' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '7月' },
            { text: '' },
            { text: '4勝0敗0S0H' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '8月' },
            { text: '' },
            { text: '4勝0敗0S0H' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { img: '/img/minus_icon.png' },
            { text: '9月' },
            { text: '' },
            { text: '4勝0敗0S0H' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/7(土)' },
            { img: '/img/Swallow.png' },
            { text: '○' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/13(金)' },
            { img: '/img/Carp.png' },
            { text: '○' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/20(金)' },
            { img: '/img/DeNA.png' },
            { text: '○' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/28(土)' },
            { img: '/img/Swallow.png' },
            { text: '○' },
            { text: 0 },
            { text: 26 },
            { text: 34 },
            { text: 137 },
            { text: 19 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
            { text: 1 },
        ]
    },
]

const titleResult = {
    dot: false,
    text: '打撃成績',
}
const headerResult = ['', '試合日付', '相手', '打席', '打数', '得点', '安打', '二塁打', '三塁打', '本塁打', '塁打', '打点',
    '三振', '四球', '敬遠', '死球', '犠打', '犠飛', '盗塁', '盗塁刺', '併殺打', '失策', '打率', '長打率', '出塁率', 'OPS',]
const dataResult = [
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '4月' },
            { text: '' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '5月' },
            { text: '' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '6月' },
            { text: '' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '7月' },
            { text: '' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { img: '/img/add_grey_icon.png' },
            { text: '8月' },
            { text: '' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { img: '/img/minus_icon.png' },
            { text: '9月' },
            { text: '' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/7(土)' },
            { img: '/img/Swallow.png' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/20(金)' },
            { img: '/img/Carp.png' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/28(土)' },
            { img: '/img/DeNA.png' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
    {
        item: [
            { text: '' },
            { text: '9/13(金)' },
            { img: '/img/Swallow.png' },
            { text: 0 },
            { text: 26 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: 0 },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
            { text: '.326' },
        ]
    },
]

class GameLogs extends Component {
    render() {
        return (
            <div className="gamelogs">
                <div className="gamelogs-control">
                    <select className="form-control">
                        <option>2019</option>
                        <option>2018</option>
                        <option>2017</option>
                        <option>2016</option>
                    </select>
                    <div className="block-button">
                        <button type="button">CSVダウンロード</button>
                    </div>
                </div>
                <div className="gamelogs-content">
                    <Table header={headerPerformance} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataPerformance} isShowOptionTable={false} titleTable={titlePerformance} />
                    <Table header={headerResult} showPagination={false} showCheckbox={false} showSearch={false} itemOfPage={dataResult} isShowOptionTable={false} titleTable={titleResult} />
                </div>
            </div>
        )
    }
}

export default withLocalize(GameLogs);